language: bash

addons:
  apt:
    packages:
      - dejagnu
      - tcllib
      # packages enabling more stuff to test:
      - perl-doc  # for perldoc to actually work

script:
  - cd test
  - ./runCompletion
  - ./runInstall
  - ./runUnit
