language: generic

sudo: required

services:
  - docker

env:
  - DIST=centos6
  - DIST=fedoradev
  - DIST=ubuntu14

before_install:
  - docker pull vskytta/bash-completion:$DIST

script:
  - docker run -t
    -e CI=true -e DIST=$DIST
    -v $PWD:/work
    -w /work
    vskytta/bash-completion:$DIST test/docker/docker-script.sh
