language: generic

sudo: required

services:
  - docker

env:
  - DIST=centos6
  - DIST=fedoradev
  - DIST=ubuntu14

before_install:
  - docker build -t bashcomp:$DIST -f test/docker/Dockerfile-$DIST .

script:
  - docker run -e CI=true -e DIST=$DIST -t bashcomp:$DIST test/docker/docker-script.sh
