language: bash

addons:
  apt:
    packages:
      - dejagnu
      - tcllib
      # packages enabling more stuff to test:
      - perl-doc  # for perldoc to actually work
      - ri        # avoid the Travis default

script:
  - cd test
  - export PATH="/usr/bin:$PATH"  # avoid Travis default ri etc
  - ./runCompletion
  - ./runInstall
  - ./runUnit
