language: bash

addons:
  apt:
    packages:
      - dejagnu
      - tcllib
      # List of packages enabling more stuff to test follows.
      # Note that all of these may not be installable via the apt addon, but
      # we should have filed an issue for all that are not. They'll trickle
      # in later when/if approved. More info:
      # https://github.com/travis-ci/apt-package-whitelist
      - a2ps
      - abook
      - acpi
      - apache2.2-common
      - apache2-utils
      - apt-build
      - asciidoc
      - aspell
      - bc
      - bind9-host
      - bluez
      - bridge-utils
      - cfengine2
      - chkconfig
      - chrony
      - chrpath
      - cksfv
      - clisp
      - cowsay
      - cppcheck
      - cups-bsd
      - cups-client
      - cvs
      - cvsps
      - desktop-file-utils
      - dict
      - dselect
      - dsniff
      - enscript
      - eog
      - evince
      - fbi
      - feh
      - file-roller
      - finger
      - gcj-jdk
      - gcl
      - gdb
      - genisoimage
      - gkrellm
      - gnat-4.6
      - gnokii-cli
      - gnome-mplayer
      - gperf
      - gphoto2
      - graphviz
      - growisofs
      - grub
      - hddtemp
      - htop
      - idn
      - iftop
      - info
      - iperf
      - ipmitool
      - iputils-arping
      - iputils-ping
      - ipv6calc
      - isc-dhcp-client
      - jpegoptim
      - k3b
      - kcov
      - kplayer
      - ldap-utils
      - lftp
      - libuser
      - lilo
      - links
      - lrzip
      - lvm2
      - lzip
      - mailman
      - mc
      - mcrypt
      - mdadm
      - medusa
      - mencoder
      - mii-diag
      - minicom
      - monodevelop
      - mplayer-gui
      - mtx
      - mussh
      - net-tools
      - nfs-common
      - open-iscsi-utils
      - openswan
      - optipng
      - p7zip-full
      - patchutils
      - perl-doc  # for perldoc to actually work
      - pinfo
      - poppler-utils
      - postfix
      - prelink
      - protobuf-compiler
      # TODO: "puppet agent --" test fails for some non-obvious reason
      #- puppet-common
      - pwgen
      - pyflakes
      - pylint
      - quota
      - rcs
      - rdesktop
      - reportbug
      - reptyr
      - ri        # avoid the Travis default
      - rpm
      - unixodbc
      - wireless-tools
      - wodim
      - yum-utils

script:
  - cd test
  - export PATH="/usr/bin:$PATH"  # avoid Travis default ri etc
  - ./runCompletion --all
  - ./runInstall --all
  - ./runUnit --all
