language: bash

addons:
  apt:
    packages:
      - dejagnu
      - tcllib
      # List of packages enabling more stuff to test follows.
      # Note that all of these may not be installable via the apt addon, but
      # we should have filed an issue for all that are not. They'll trickle
      # in later when/if approved. More info:
      # https://github.com/travis-ci/apt-package-whitelist
      - a2ps
      - abook
      - acpi
      - apache2.2-common
      - apt-build
      - asciidoc
      - aspell
      - bc
      - bluez
      - bridge-utils
      - cfengine2
      - chkconfig
      - chrony
      - chrpath
      - cksfv
      - clisp
      - cowsay
      - cppcheck
      - cups-client
      - cvs
      - cvsps
      - desktop-file-utils
      - dict
      - dselect
      - dsniff
      - enscript
      - eog
      - evince
      - fbi
      - feh
      - file-roller
      - finger
      - gcj-jdk
      - gcl
      - gdb
      - genisoimage
      - gkrellm
      - gnat-4.6
      - gnokii-cli
      - gnome-mplayer
      - gperf
      - gphoto2
      - graphviz
      - growisofs
      - grub
      - iputils-arping
      - isc-dhcp-client
      - mailman
      - mplayer-gui
      - p7zip-full
      - perl-doc  # for perldoc to actually work
      - rcs
      - ri        # avoid the Travis default
      - rpm
      - wodim

script:
  - cd test
  - export PATH="/usr/bin:$PATH"  # avoid Travis default ri etc
  - ./runCompletion --all
  - ./runInstall --all
  - ./runUnit --all
