language: bash

addons:
  apt:
    packages:
      - dejagnu
      - tcllib
      # packages enabling more stuff to test:
      - a2ps
      - abook
      - acpi
      - apache2.2-common
      - apt-build
      - asciidoc
      - aspell
      - bc
      - bridge-utils
      - dsniff
      - iputils-arping
      - mailman
      - p7zip-full
      - perl-doc  # for perldoc to actually work
      - ri        # avoid the Travis default

script:
  - cd test
  - export PATH="/usr/bin:$PATH"  # avoid Travis default ri etc
  - ./runCompletion --all
  - ./runInstall --all
  - ./runUnit --all
